[package]
name = "rapl"
version = "0.1.0"
edition = "2021"
description = "A Rank polymorphic array library for Rust"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
